/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ece422_project1_variants_InsertionSort */

#ifndef _Included_ece422_project1_variants_InsertionSort
#define _Included_ece422_project1_variants_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
#undef ece422_project1_variants_InsertionSort_MIN_PRIORITY
#define ece422_project1_variants_InsertionSort_MIN_PRIORITY 1L
#undef ece422_project1_variants_InsertionSort_NORM_PRIORITY
#define ece422_project1_variants_InsertionSort_NORM_PRIORITY 5L
#undef ece422_project1_variants_InsertionSort_MAX_PRIORITY
#define ece422_project1_variants_InsertionSort_MAX_PRIORITY 10L
/*
 * Class:     ece422_project1_variants_InsertionSort
 * Method:    sort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_ece422_project1_variants_InsertionSort_sort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
